[build]
  publish = "build"
  command = "CI=false GENERATE_SOURCEMAP=false npm run build"
  base = "frontend"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"

# EXE dosyaları için özel ayarlar
[[headers]]
  for = "/*.exe"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

# VoidScanner.exe için özel ayarlar
[[headers]]
  for = "/VoidScanner.exe"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

# DynamicPathScanner.exe için özel ayarlar
[[headers]]
  for = "/DynamicPathScanner.exe"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

# SimpleScanner.exe için özel ayarlar
[[headers]]
  for = "/SimpleScanner.exe"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

# Güvenlik başlıkları
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
