[build]
  publish = "build"
  command = "CI=false GENERATE_SOURCEMAP=false npm run build"
  base = "frontend"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
